# ----
# Site

name:
title: Base
url: "https://javanile.org/package-manager/"
baseurl:
google_analytics_key:
disqus_shortname:
newsletter_action:

navigation:
  - name: Cavallo
    link: /
  - name: Videos
    link: /videos/
  - name: FAQ
    link: /faq/

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: "https://raw.githubusercontent.com/javanile/package-manager/main/assets/images/logo.png"
description: Knowledge base template for Jekyll.
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Base Template
  links:
    - https://github.com/CloudCannon/base-jekyll-template

primary_color: "#000"

# -----
# Build

timezone: Etc/UTC

permalink: /:categories/:title/

plugins:
  - jekyll-extract-element
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENCE
  - vendor

collections:
  sets:

jekyll-archives:
  enabled: ['categories']

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      comments: true
  -
    scope:
      type: "sets"
    values:
      _hide_content: true
  -
    scope:
      path: "index.html"
    values:
      body_class: "show_hero_search"

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - Email
  - RSS

types:
  - Document
  - Video

_comments:

theme: null
