---

name: package-manager
title: Package Manager
url: https://javanile.org/package-manager/
baseurl:
logo: https://raw.githubusercontent.com/javanile/package-manager/main/assets/images/logo.png

google_analytics_key:
disqus_shortname:
newsletter_action:


# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
description: Knowledge base template for Jekyll.
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Base Template
  links:
    - https://github.com/CloudCannon/base-jekyll-template

#primary_color: "#000"
#secondary_color: "#EEE"

# -----
# Build

timezone: Etc/UTC

permalink: /:categories/:title/

plugins:
  - jekyll-extract-element
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENCE
  - vendor/*
  - packages/*


defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      comments: true
  -
    scope:
      type: "sets"
    values:
      _hide_content: true
  -
    scope:
      path: "index.html"
    values:
      body_class: "show_hero_search"

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - Email
  - RSS

types:
  - Document
  - Video

_comments:

theme: null

footer_links:
  - name:
    link: https://facebook.com/cloudcannon
    social_icon: Facebook
    new_window: true
  - name:
    link: https://twitter.com/cloudcannon
    social_icon: Twitter
    new_window: true
  - name:
    link: https://youtube.com/c/cloudcannon
    social_icon: YouTube
    new_window: true
  - name:
    link: https://instagram.com/
    social_icon: Instagram
    new_window: true

collections:
  categories:
    output: true
    permalink: /:collection/:name
  packages:
    output: true
    permalink: /:collection/:name

jekyll-archives:
  enabled:
    - categories
    - tags
  permalinks:
    category: /cat/:name/
