---

title: My Packages
description: A minimal package manager site.

repository: javanile/package-manager

plugins:
  - jekyll-remote-theme

remote_theme: javanile/package-manager@main

collections:
  packages:
    output: true
    permalink: /:collection/:name
  categories:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "index.html"
    values:
      body_class: "show_hero_search"