---
name: Remote

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          mv test/remote_theme /tmp/
          rm -fr ./
          mv test/remote_theme/* ./
      - uses: jerryjvl/jekyll-build-action@v1
