---
name: remote_theme

on:
  push:
    branches:
      - main

jobs:
  build:
    name: remote_theme
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: mv test/remote_theme /tmp/ && rm -fr ./* && mv /tmp/remote_theme/* ./
      - uses: javanile/jekyll-build-action@main
