---
name: Remote

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build
        uses: jerryjvl/jekyll-build-action@v1
        working-directory: test/remote_theme
